blank_issues_enabled: false
contact_links:
  - name: Upcoming Media Lovelace Card Support
    url: https://github.com/custom-cards/upcoming-media-card/issues
    about: Please ask for assistance about Upcoming Media card here.